SELECT p.IME, p.PREZIME, pp.ID_PRIVATNE_SOBE, k.SPECIJALNOST
FROM PRIVATNI_PACIJENT AS pp
JOIN PACIJENT AS p ON p.OIB = pp.OIB
JOIN KONZULTANT AS k ON k.OIB = pp.OIB_KONZULTANTA
WHERE pp.OIB_KONZULTANTA = '90000000001';
