SELECT k.OIB, k.PREZIME, k.IME, k.ADRESA, k.BROJ_TELEFONA, c.SPECIJALNOST
FROM KIRURG AS k
JOIN NADGLEDA AS n
ON n.OIB_NADGLEDANOG = k.OIB
JOIN KONZULTANT AS c
ON c.OIB = n.OIB_KONZULTANTA
WHERE n.OIB_KONZULTANTA = '90000000001';
