WITH BROJ_OPERACIJA AS (
SELECT
K.OIB,
K.IME,
K.PREZIME,
COUNT(*) AS BROJ_OPERACIJA
FROM KIRURG AS K
JOIN OPERACIJA AS O
ON O.OIB_KIRURGA = K.OIB
WHERE O.DATUM BETWEEN '2026-01-01' AND '2026-06-30'
GROUP BY K.OIB, K.IME, K.PREZIME
)
SELECT
OIB,
IME,
PREZIME,
BROJ_OPERACIJA
FROM BROJ_OPERACIJA
WHERE BROJ_OPERACIJA = (
SELECT MAX(BROJ_OPERACIJA)
FROM BROJ_OPERACIJA
);
