WITH BROJ_OPERACIJA AS (
SELECT
OIB_KIRURGA,
COUNT(*) AS BROJ_OPERACIJA
FROM OPERACIJA
WHERE DATUM BETWEEN '2026-01-01' AND '2026-06-30'
GROUP BY OIB_KIRURGA
)
SELECT
K.OIB,
K.IME,
K.PREZIME,
B.BROJ_OPERACIJA
FROM KIRURG AS K
JOIN BROJ_OPERACIJA AS B
ON B.OIB_KIRURGA = K.OIB
WHERE B.BROJ_OPERACIJA = (
SELECT MAX(BROJ_OPERACIJA)
FROM BROJ_OPERACIJA
);
