SELECT
s.ID_SOBE,
s.BROJ_KREVETA,
COUNT(p.OIB) AS BROJ_TRENUTNO_SMJESTENIH_PACIJENATA,
s.BROJ_KREVETA - COUNT(p.OIB) AS BROJ_SLOBODNIH_KREVETA
FROM SOBA AS s
LEFT JOIN PACIJENT AS p
ON p.ID_SOBE = s.ID_SOBE
GROUP BY
s.ID_SOBE,
s.BROJ_KREVETA;
