SELECT k.OIB, k.PREZIME, k.IME
FROM KIRURG AS k
JOIN KONZULTANT AS c ON c.OIB = k.OIB
WHERE EXISTS (
SELECT 1
FROM PRIVATNI_PACIJENT AS pp
WHERE pp.OIB_KONZULTANTA = c.OIB
)
AND NOT EXISTS (
SELECT 1
FROM PRIVATNI_PACIJENT AS pp
WHERE pp.OIB_KONZULTANTA = c.OIB
AND NOT EXISTS (
SELECT 1
FROM OPERACIJA AS o
WHERE o.OIB_KIRURGA = c.OIB
AND o.OIB_PACIJENTA = pp.OIB
)
);
