SELECT k.OIB, k.SPECIJALNOST
FROM KONZULTANT AS k
WHERE EXISTS (
SELECT 1
FROM PRIVATNI_PACIJENT AS pp
WHERE pp.OIB_KONZULTANTA = k.OIB
)
AND NOT EXISTS (
SELECT 1
FROM PRIVATNI_PACIJENT AS pp
WHERE pp.OIB_KONZULTANTA = k.OIB
AND NOT EXISTS (
SELECT 1
FROM OPERACIJA AS o
WHERE o.OIB_KIRURGA = k.OIB
AND o.OIB_PACIJENTA = pp.OIB
)
);
