WITH broj_asistenata AS (
SELECT
o.ID_OPERACIJE,
o.TIP_OPERACIJE,
o.OIB_KIRURGA,
COUNT(a.OIB_KIRURGA) AS BROJ_ASISTENATA
FROM OPERACIJA AS o
LEFT JOIN ASISTIRA AS a
ON a.ID_OPERACIJE = o.ID_OPERACIJE
GROUP BY
o.ID_OPERACIJE,
o.TIP_OPERACIJE,
o.OIB_KIRURGA
)
SELECT
b.TIP_OPERACIJE,
k.OIB,
k.PREZIME,
k.IME,
b.BROJ_ASISTENATA
FROM broj_asistenata AS b
JOIN KIRURG AS k
ON k.OIB = b.OIB_KIRURGA
WHERE b.BROJ_ASISTENATA > (
SELECT AVG(BROJ_ASISTENATA)
FROM broj_asistenata
);
