SELECT
o.TIP_OPERACIJE,
o.OIB_KIRURGA,
COUNT(a.OIB_KIRURGA) AS BROJ_ASISTENATA
FROM OPERACIJA AS o
LEFT JOIN ASISTIRA AS a
ON a.ID_OPERACIJE = o.ID_OPERACIJE
GROUP BY
o.ID_OPERACIJE,
o.TIP_OPERACIJE,
o.OIB_KIRURGA
HAVING COUNT(a.OIB_KIRURGA) > (
SELECT AVG(x.BROJ_ASISTENATA)
FROM (
SELECT
o2.ID_OPERACIJE,
COUNT(a2.OIB_KIRURGA) AS BROJ_ASISTENATA
FROM OPERACIJA AS o2
LEFT JOIN ASISTIRA AS a2
ON a2.ID_OPERACIJE = o2.ID_OPERACIJE
GROUP BY o2.ID_OPERACIJE
) AS x
);
