WITH BROJ_ASISTENATA AS (
SELECT
O.ID_OPERACIJE,
O.TIP_OPERACIJE,
O.OIB_KIRURGA,
COUNT(A.OIB_KIRURGA) AS BROJ_ASISTENATA
FROM OPERACIJA AS O
LEFT JOIN ASISTIRA AS A
ON A.ID_OPERACIJE = O.ID_OPERACIJE
GROUP BY
O.ID_OPERACIJE,
O.TIP_OPERACIJE,
O.OIB_KIRURGA
)
SELECT
B.TIP_OPERACIJE,
K.PREZIME,
K.IME,
B.BROJ_ASISTENATA
FROM BROJ_ASISTENATA AS B
JOIN KIRURG AS K
ON K.OIB = B.OIB_KIRURGA
WHERE B.BROJ_ASISTENATA > (
SELECT AVG(B2.BROJ_ASISTENATA)
FROM BROJ_ASISTENATA AS B2
);
