DROP DATABASE IF EXISTS diplomski_bolnica_test;

CREATE DATABASE diplomski_bolnica_test
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE diplomski_bolnica_test;


CREATE TABLE SOBA (
    ID_SOBE VARCHAR(5) NOT NULL,
    TIP_SOBE VARCHAR(50) NOT NULL,
    BROJ_KREVETA SMALLINT UNSIGNED NOT NULL,

    CONSTRAINT pk_soba
        PRIMARY KEY (ID_SOBE),

    CONSTRAINT chk_soba_broj_kreveta
        CHECK (BROJ_KREVETA > 0)
) ENGINE = InnoDB;


CREATE TABLE SALA (
    ID_SALE VARCHAR(5) NOT NULL,
    TIP_SALE VARCHAR(50) NOT NULL,

    CONSTRAINT pk_sala
        PRIMARY KEY (ID_SALE)
) ENGINE = InnoDB;


CREATE TABLE KIRURG (
    OIB CHAR(11) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    IME VARCHAR(50) NOT NULL,
    ADRESA VARCHAR(100) NULL,
    BROJ_TELEFONA VARCHAR(30) NULL,

    CONSTRAINT pk_kirurg
        PRIMARY KEY (OIB),

    CONSTRAINT chk_kirurg_oib
        CHECK (OIB REGEXP '^[0-9]{11}$')
) ENGINE = InnoDB;


CREATE TABLE KONZULTANT (
    OIB CHAR(11) NOT NULL,
    SPECIJALNOST VARCHAR(100) NOT NULL,

    CONSTRAINT pk_konzultant
        PRIMARY KEY (OIB),

    CONSTRAINT fk_konzultant_kirurg
        FOREIGN KEY (OIB)
        REFERENCES KIRURG(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE PACIJENT (
    OIB CHAR(11) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    IME VARCHAR(50) NOT NULL,
    ID_SOBE VARCHAR(5) NULL,
    ADRESA VARCHAR(100) NULL,
    DATUM_RODJENJA DATE NOT NULL,
    SPOL ENUM('M', 'Z') NOT NULL,

    CONSTRAINT pk_pacijent
        PRIMARY KEY (OIB),

    CONSTRAINT chk_pacijent_oib
        CHECK (OIB REGEXP '^[0-9]{11}$'),

    CONSTRAINT fk_pacijent_soba
        FOREIGN KEY (ID_SOBE)
        REFERENCES SOBA(ID_SOBE)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE PRIVATNI_PACIJENT (
    OIB CHAR(11) NOT NULL,
    OIB_KONZULTANTA CHAR(11) NOT NULL,
    ID_PRIVATNE_SOBE VARCHAR(5) NOT NULL,

    CONSTRAINT pk_privatni_pacijent
        PRIMARY KEY (OIB),

    CONSTRAINT uq_privatna_soba
        UNIQUE (ID_PRIVATNE_SOBE),

    CONSTRAINT fk_privatni_pacijent
        FOREIGN KEY (OIB)
        REFERENCES PACIJENT(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_privatni_konzultant
        FOREIGN KEY (OIB_KONZULTANTA)
        REFERENCES KONZULTANT(OIB)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE SESTRA (
    OIB CHAR(11) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    IME VARCHAR(50) NOT NULL,
    STRUCNI_STUPANJ ENUM('SSS', 'VSHS', 'VSS') NOT NULL,

    CONSTRAINT pk_sestra
        PRIMARY KEY (OIB),

    CONSTRAINT chk_sestra_oib
        CHECK (OIB REGEXP '^[0-9]{11}$')
) ENGINE = InnoDB;


CREATE TABLE OPERACIJA (
    ID_OPERACIJE INT UNSIGNED NOT NULL,
    OIB_KIRURGA CHAR(11) NOT NULL,
    ID_SALE VARCHAR(5) NOT NULL,
    OIB_PACIJENTA CHAR(11) NOT NULL,
    TIP_OPERACIJE VARCHAR(100) NOT NULL,
    DATUM DATE NOT NULL,
    VRIJEME TIME NOT NULL,

    CONSTRAINT pk_operacija
        PRIMARY KEY (ID_OPERACIJE),

    CONSTRAINT fk_operacija_kirurg
        FOREIGN KEY (OIB_KIRURGA)
        REFERENCES KIRURG(OIB)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_operacija_sala
        FOREIGN KEY (ID_SALE)
        REFERENCES SALA(ID_SALE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_operacija_pacijent
        FOREIGN KEY (OIB_PACIJENTA)
        REFERENCES PACIJENT(OIB)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE ASISTIRA (
    ID_OPERACIJE INT UNSIGNED NOT NULL,
    OIB_KIRURGA CHAR(11) NOT NULL,
    ULOGA VARCHAR(100) NOT NULL,

    CONSTRAINT pk_asistira
        PRIMARY KEY (ID_OPERACIJE, OIB_KIRURGA),

    CONSTRAINT fk_asistira_operacija
        FOREIGN KEY (ID_OPERACIJE)
        REFERENCES OPERACIJA(ID_OPERACIJE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_asistira_kirurg
        FOREIGN KEY (OIB_KIRURGA)
        REFERENCES KIRURG(OIB)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE NADGLEDA (
    OIB_NADGLEDANOG CHAR(11) NOT NULL,
    OIB_KONZULTANTA CHAR(11) NOT NULL,

    CONSTRAINT pk_nadgleda
        PRIMARY KEY (OIB_NADGLEDANOG),

    CONSTRAINT fk_nadgleda_kirurg
        FOREIGN KEY (OIB_NADGLEDANOG)
        REFERENCES KIRURG(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_nadgleda_konzultant
        FOREIGN KEY (OIB_KONZULTANTA)
        REFERENCES KONZULTANT(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT chk_nadgleda_sebe
        CHECK (OIB_NADGLEDANOG <> OIB_KONZULTANTA)
) ENGINE = InnoDB;


CREATE TABLE ZADUZENA_ZA_SOBU (
    OIB_SESTRE CHAR(11) NOT NULL,
    ID_SOBE VARCHAR(5) NOT NULL,
    DATUM_ZADUZIVANJA DATE NOT NULL,

    CONSTRAINT pk_zaduzena_za_sobu
        PRIMARY KEY (OIB_SESTRE),

    CONSTRAINT fk_zs_sestra
        FOREIGN KEY (OIB_SESTRE)
        REFERENCES SESTRA(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_zs_soba
        FOREIGN KEY (ID_SOBE)
        REFERENCES SOBA(ID_SOBE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;


CREATE TABLE ZADUZENA_ZA_SALU (
    OIB_SESTRE CHAR(11) NOT NULL,
    ID_SALE VARCHAR(5) NOT NULL,
    DATUM_ZADUZIVANJA DATE NOT NULL,

    CONSTRAINT pk_zaduzena_za_salu
        PRIMARY KEY (OIB_SESTRE),

    CONSTRAINT fk_zsal_sestra
        FOREIGN KEY (OIB_SESTRE)
        REFERENCES SESTRA(OIB)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_zsal_sala
        FOREIGN KEY (ID_SALE)
        REFERENCES SALA(ID_SALE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;


DELIMITER //

CREATE TRIGGER trg_asistira_insert
BEFORE INSERT ON ASISTIRA
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM OPERACIJA
        WHERE ID_OPERACIJE = NEW.ID_OPERACIJE
          AND OIB_KIRURGA = NEW.OIB_KIRURGA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'Glavni kirurg ne može biti asistent na istoj operaciji.';
    END IF;
END//


CREATE TRIGGER trg_asistira_update
BEFORE UPDATE ON ASISTIRA
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM OPERACIJA
        WHERE ID_OPERACIJE = NEW.ID_OPERACIJE
          AND OIB_KIRURGA = NEW.OIB_KIRURGA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'Glavni kirurg ne može biti asistent na istoj operaciji.';
    END IF;
END//


CREATE TRIGGER trg_operacija_kirurg_update
BEFORE UPDATE ON OPERACIJA
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM ASISTIRA
        WHERE ID_OPERACIJE = NEW.ID_OPERACIJE
          AND OIB_KIRURGA = NEW.OIB_KIRURGA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'Kirurg je već evidentiran kao asistent na toj operaciji.';
    END IF;
END//

DELIMITER ;
