SELECT
p.ID_POSUDBE,
p.DATUM_POSUDBE,
p.PREDVIDENI_POVRAT,
p.STVARNI_POVRAT,
c.BROJ_ISKAZNICE,
c.OIB,
c.IME,
c.PREZIME,
c.ADRESA,
c.EMAIL,
c.DATUM_UCLANJENJA,
c.STATUS_CLANSTVA,
pr.INVENTARNI_BROJ,
pr.ID_NASLOVA,
pr.DATUM_NABAVE,
pr.STATUS_PRIMJERKA
FROM POSUDBA AS p
JOIN ZAPOSLENIK AS z
ON z.ID_ZAPOSLENIKA = p.ID_ZAPOSLENIKA
JOIN CLAN AS c
ON c.BROJ_ISKAZNICE = p.BROJ_ISKAZNICE
JOIN PRIMJERAK AS pr
ON pr.INVENTARNI_BROJ = p.INVENTARNI_BROJ
WHERE p.DATUM_POSUDBE = '2026-06-05'
AND z.OIB = '90111111111';
