SELECT DISTINCT n.ID_NASLOVA, n.ISBN, n.NASLOV, n.GODINA_IZDANJA, n.IZDAVAC
FROM POSUDBA AS po
JOIN PRIMJERAK AS pr
ON pr.INVENTARNI_BROJ = po.INVENTARNI_BROJ
JOIN NASLOV AS n
ON n.ID_NASLOVA = pr.ID_NASLOVA
WHERE po.BROJ_ISKAZNICE = 'C001'
AND po.STVARNI_POVRAT IS NULL;
