SELECT
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME,
n.NASLOV,
p.PREDVIDENI_POVRAT,
p.STVARNI_POVRAT
FROM POSUDBA AS p
JOIN CLAN AS c
ON c.BROJ_ISKAZNICE = p.BROJ_ISKAZNICE
JOIN PRIMJERAK AS pr
ON pr.INVENTARNI_BROJ = p.INVENTARNI_BROJ
JOIN NASLOV AS n
ON n.ID_NASLOVA = pr.ID_NASLOVA
WHERE p.STVARNI_POVRAT > p.PREDVIDENI_POVRAT;
