WITH aktivne_posudbe AS (
SELECT
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME,
COUNT(*) AS BROJ_AKTIVNIH_POSUDBI
FROM CLAN AS c
JOIN POSUDBA AS p
ON p.BROJ_ISKAZNICE = c.BROJ_ISKAZNICE
WHERE p.STVARNI_POVRAT IS NULL
GROUP BY
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME
)
SELECT
BROJ_ISKAZNICE,
IME,
PREZIME,
BROJ_AKTIVNIH_POSUDBI
FROM aktivne_posudbe
WHERE BROJ_AKTIVNIH_POSUDBI = (
SELECT MAX(BROJ_AKTIVNIH_POSUDBI)
FROM aktivne_posudbe
);
