WITH broj_aktivnih AS (
SELECT
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME,
COUNT(p.ID_POSUDBE) AS BROJ_AKTIVNIH_POSUDBI
FROM CLAN AS c
LEFT JOIN POSUDBA AS p
ON p.BROJ_ISKAZNICE = c.BROJ_ISKAZNICE
AND p.STVARNI_POVRAT IS NULL
GROUP BY
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME
)
SELECT
BROJ_ISKAZNICE,
IME,
PREZIME,
BROJ_AKTIVNIH_POSUDBI
FROM broj_aktivnih
WHERE BROJ_AKTIVNIH_POSUDBI = (
SELECT MAX(BROJ_AKTIVNIH_POSUDBI)
FROM broj_aktivnih
);
