WITH aktivne_posudbe AS (
SELECT
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME,
COUNT(p.ID_POSUDBE) AS BROJ_AKTIVNIH_POSUDBI
FROM CLAN AS c
LEFT JOIN POSUDBA AS p
ON p.BROJ_ISKAZNICE = c.BROJ_ISKAZNICE
AND p.STVARNI_POVRAT IS NULL
GROUP BY
c.BROJ_ISKAZNICE,
c.IME,
c.PREZIME
),
rangirano AS (
SELECT
BROJ_ISKAZNICE,
IME,
PREZIME,
BROJ_AKTIVNIH_POSUDBI,
DENSE_RANK() OVER (ORDER BY BROJ_AKTIVNIH_POSUDBI DESC) AS RANG
FROM aktivne_posudbe
)
SELECT
BROJ_ISKAZNICE,
IME,
PREZIME,
BROJ_AKTIVNIH_POSUDBI
FROM rangirano
WHERE RANG = 1;
