SELECT
n.NASLOV,
COUNT(DISTINCT p.INVENTARNI_BROJ) AS UKUPAN_BROJ_PRIMJERAKA,
COUNT(DISTINCT CASE
WHEN po.ID_POSUDBE IS NOT NULL THEN p.INVENTARNI_BROJ
END) AS BROJ_PRIMJERAKA_AKTIVNA_POSUDBA,
COUNT(DISTINCT p.INVENTARNI_BROJ) -
COUNT(DISTINCT CASE
WHEN po.ID_POSUDBE IS NOT NULL THEN p.INVENTARNI_BROJ
END) AS BROJ_PRIMJERAKA_BEZ_AKTIVNE_POSUDBE
FROM NASLOV AS n
LEFT JOIN PRIMJERAK AS p
ON p.ID_NASLOVA = n.ID_NASLOVA
LEFT JOIN POSUDBA AS po
ON po.INVENTARNI_BROJ = p.INVENTARNI_BROJ
AND po.STVARNI_POVRAT IS NULL
GROUP BY n.ID_NASLOVA, n.NASLOV;
