SELECT
n.NASLOV,
COUNT(p.INVENTARNI_BROJ) AS UKUPAN_BROJ_PRIMJERAKA,
SUM(
CASE
WHEN p.INVENTARNI_BROJ IS NOT NULL
AND EXISTS (
SELECT 1
FROM POSUDBA po
WHERE po.INVENTARNI_BROJ = p.INVENTARNI_BROJ
AND po.STVARNI_POVRAT IS NULL
)
THEN 1
ELSE 0
END
) AS BROJ_PRIMJERAKA_AKTIVNO_POSUDENIH,
SUM(
CASE
WHEN p.INVENTARNI_BROJ IS NOT NULL
AND NOT EXISTS (
SELECT 1
FROM POSUDBA po
WHERE po.INVENTARNI_BROJ = p.INVENTARNI_BROJ
AND po.STVARNI_POVRAT IS NULL
)
THEN 1
ELSE 0
END
) AS BROJ_PRIMJERAKA_BEZ_AKTIVNE_POSUDBE
FROM NASLOV n
LEFT JOIN PRIMJERAK p
ON p.ID_NASLOVA = n.ID_NASLOVA
GROUP BY n.ID_NASLOVA, n.NASLOV;
