SELECT c.BROJ_ISKAZNICE, c.OIB, c.IME, c.PREZIME, c.ADRESA, c.EMAIL,
c.DATUM_UCLANJENJA, c.STATUS_CLANSTVA
FROM CLAN AS c
WHERE NOT EXISTS (
SELECT 1
FROM NASLOV_AUTOR AS na
WHERE na.ID_AUTORA = 201
AND NOT EXISTS (
SELECT 1
FROM POSUDBA AS po
JOIN PRIMJERAK AS pr
ON pr.INVENTARNI_BROJ = po.INVENTARNI_BROJ
WHERE po.BROJ_ISKAZNICE = c.BROJ_ISKAZNICE
AND pr.ID_NASLOVA = na.ID_NASLOVA
)
);
