SELECT
BROJ_ISKAZNICE,
COUNT(*) AS BROJ_ZAKASNJELIH_POSUDBI,
AVG(DATEDIFF(STVARNI_POVRAT, PREDVIDENI_POVRAT)) AS PROSJECAN_BROJ_DANA_KASNJENJA
FROM POSUDBA
WHERE STVARNI_POVRAT IS NOT NULL
AND STVARNI_POVRAT > PREDVIDENI_POVRAT
GROUP BY BROJ_ISKAZNICE
HAVING COUNT(*) >= 3
AND AVG(DATEDIFF(STVARNI_POVRAT, PREDVIDENI_POVRAT)) >
(
SELECT AVG(DATEDIFF(STVARNI_POVRAT, PREDVIDENI_POVRAT))
FROM POSUDBA
WHERE STVARNI_POVRAT IS NOT NULL
AND STVARNI_POVRAT > PREDVIDENI_POVRAT
);
