SELECT
p.BROJ_ISKAZNICE,
COUNT(*) AS BROJ_ZAKASNJELIH_POSUDBI,
AVG(DATEDIFF(p.STVARNI_POVRAT, p.PREDVIDENI_POVRAT)) AS PROSJECAN_BROJ_DANA_KASNJENJA
FROM POSUDBA AS p
WHERE p.STVARNI_POVRAT IS NOT NULL
AND p.STVARNI_POVRAT > p.PREDVIDENI_POVRAT
GROUP BY p.BROJ_ISKAZNICE
HAVING COUNT(*) >= 3
AND AVG(DATEDIFF(p.STVARNI_POVRAT, p.PREDVIDENI_POVRAT)) >
(
SELECT AVG(DATEDIFF(p2.STVARNI_POVRAT, p2.PREDVIDENI_POVRAT))
FROM POSUDBA AS p2
WHERE p2.STVARNI_POVRAT IS NOT NULL
AND p2.STVARNI_POVRAT > p2.PREDVIDENI_POVRAT
);
