WITH broj_posudbi AS (
SELECT
YEAR(p.DATUM_POSUDBE) AS godina,
MONTH(p.DATUM_POSUDBE) AS mjesec,
z.ID_ZAPOSLENIKA,
z.OIB,
z.IME,
z.PREZIME,
z.RADNO_MJESTO,
COUNT(*) AS broj_evidentiranih_posudbi
FROM POSUDBA AS p
JOIN ZAPOSLENIK AS z
ON z.ID_ZAPOSLENIKA = p.ID_ZAPOSLENIKA
WHERE p.DATUM_POSUDBE >= '2026-01-01'
AND p.DATUM_POSUDBE < '2027-01-01'
GROUP BY
YEAR(p.DATUM_POSUDBE),
MONTH(p.DATUM_POSUDBE),
z.ID_ZAPOSLENIKA,
z.OIB,
z.IME,
z.PREZIME,
z.RADNO_MJESTO
),
rangirano AS (
SELECT
broj_posudbi.*,
DENSE_RANK() OVER (
PARTITION BY godina, mjesec
ORDER BY broj_evidentiranih_posudbi DESC
) AS rang
FROM broj_posudbi
)
SELECT
godina,
mjesec,
ID_ZAPOSLENIKA,
OIB,
IME,
PREZIME,
RADNO_MJESTO,
broj_evidentiranih_posudbi
FROM rangirano
WHERE rang = 1
ORDER BY godina, mjesec, ID_ZAPOSLENIKA;
