WITH broj_posudbi AS (
SELECT
YEAR(p.DATUM_POSUDBE) AS GODINA,
MONTH(p.DATUM_POSUDBE) AS MJESEC,
z.ID_ZAPOSLENIKA,
z.OIB,
z.IME,
z.PREZIME,
z.RADNO_MJESTO,
COUNT(*) AS BROJ_POSUDBI
FROM POSUDBA AS p
JOIN ZAPOSLENIK AS z
ON z.ID_ZAPOSLENIKA = p.ID_ZAPOSLENIKA
WHERE p.DATUM_POSUDBE >= '2026-01-01'
AND p.DATUM_POSUDBE < '2027-01-01'
GROUP BY
YEAR(p.DATUM_POSUDBE),
MONTH(p.DATUM_POSUDBE),
z.ID_ZAPOSLENIKA,
z.OIB,
z.IME,
z.PREZIME,
z.RADNO_MJESTO
),
rangirano AS (
SELECT
GODINA,
MJESEC,
ID_ZAPOSLENIKA,
OIB,
IME,
PREZIME,
RADNO_MJESTO,
BROJ_POSUDBI,
DENSE_RANK() OVER (
PARTITION BY GODINA, MJESEC
ORDER BY BROJ_POSUDBI DESC
) AS RANG
FROM broj_posudbi
)
SELECT
GODINA,
MJESEC,
ID_ZAPOSLENIKA,
OIB,
IME,
PREZIME,
RADNO_MJESTO,
BROJ_POSUDBI
FROM rangirano
WHERE RANG = 1
ORDER BY GODINA, MJESEC, ID_ZAPOSLENIKA;
